name: OpenWrt R2S CI
on:
  schedule:
    - cron:  '0 10 * * *'
  watch:
    types: started

jobs:
  openwrt:	
    runs-on: ubuntu-20.04	
    steps:	
    - name: 01 - clone repository
      uses: actions/checkout@v2
    - name: 02 - configure system
      run: bash script.sh
    - name: 03 - build firmware
      run: |
        cd openwrt
        let core=$(nproc)+2
        make -j${core}
    - name: 04 - error handle
      if: steps.compileopenwrt.outcome == 'failure'
      run: |
        cd openwrt
        make -j1 V=s
    - name: 05 - push to artifact file	
      uses: actions/upload-artifact@v2	
      with:	
        name: r2s
        path: openwrt/bin/targets/rockchip/armv8/
