name: OpenWrt R2S CI
on:
  watch:
    types: started

jobs:
  openwrt:	
    runs-on: ubuntu-20.04	
    steps:	
    - name: 01 - clone repository
      uses: actions/checkout@v2
    - name: 02 - configure system
      run: bash script.sh
    - name: 03 - build firmware
      id: build
      continue-on-error: true
      run: |
        cd openwrt
        cp ../.config .config
        make defconfig
        make download -j8
        let core=$(nproc)+2
        make -j${core}
        echo $?
    - name: 04 - error handle
      if: steps.build.outcome == 'failure'
      run: |
        cd openwrt
        make -j1 V=s
    - name: 05 - push to artifact file	
      uses: actions/upload-artifact@v2	
      with:	
        name: r2s-firmware
        path: openwrt/bin/targets/rockchip/armv8/*.img.gz
